repos:
  - repo: local
    hooks:
      - id: yapf-docker
        name: Format Python via Dockerized yapf
        entry: make format
        language: system
        pass_filenames: false
        always_run: true
